url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Antoine Hubert de Fraisse" # the name of your site, e.g. ACME Corp.
description: "Finance PhD Candidate at HEC Paris"
